apiVersion: v1
kind: PersistentVolume
metadata:
  name: notes-app-pv
#  Namespace: notes-app-ns
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: "/mnt/data"
