apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: notes-app-pvc
#  Namespace: notes-app-ns
spec:
  storageClassName: local-storage
  resources:
    requests:
      storage: 2Gi
  accessModes:
    - ReadWriteOnce
